package skills

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// LockfileVersion is the schema version of skills/MANIFEST.yaml.
// Bump when fields change incompatibly.
const LockfileVersion = "1"

// LockfileName is the canonical filename for the lockfile.
const LockfileName = "MANIFEST.yaml"

// LockEntry is one row in the lockfile — one skill bundle.
type LockEntry struct {
	Name        string `yaml:"name"`
	Version     string `yaml:"version"`
	Owner       string `yaml:"owner"`
	ContentHash string `yaml:"content_sha256"`
	Path        string `yaml:"path"` // relative to skills/ dir
}

// Lockfile is the full skills/MANIFEST.yaml shape.
type Lockfile struct {
	SchemaVersion string      `yaml:"schema_version"`
	GeneratedAt   string      `yaml:"generated_at"`
	Skills        []LockEntry `yaml:"skills"`
}

// BuildLockfile walks dir (typically the repo's skills/ directory),
// validates each SKILL.md, computes its SHA-256, and returns a sorted
// Lockfile struct ready to be marshaled.
//
// dir is the skills root. The returned LockEntry.Path is relative to
// dir, so the lockfile is portable.
func BuildLockfile(dir string) (Lockfile, error) {
	lf := Lockfile{
		SchemaVersion: LockfileVersion,
		GeneratedAt:   time.Now().UTC().Format(time.RFC3339),
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return lf, fmt.Errorf("read skills dir %s: %w", dir, err)
	}

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") || name == "schema" {
			continue
		}
		skillPath := filepath.Join(dir, name, "SKILL.md")
		data, err := os.ReadFile(skillPath)
		if err != nil {
			// Skill dir without SKILL.md — skip silently (validator surfaces this).
			continue
		}

		front, _, err := splitFrontmatter(data)
		if err != nil {
			return lf, fmt.Errorf("%s: %w", skillPath, err)
		}
		var fm map[string]any
		if err := yaml.Unmarshal(front, &fm); err != nil {
			return lf, fmt.Errorf("%s: parse frontmatter: %w", skillPath, err)
		}
		nameStr, _ := fm["name"].(string)
		versionStr, _ := fm["version"].(string)
		ownerStr, _ := fm["owner"].(string)

		sum := sha256.Sum256(data)

		lf.Skills = append(lf.Skills, LockEntry{
			Name:        nameStr,
			Version:     versionStr,
			Owner:       ownerStr,
			ContentHash: hex.EncodeToString(sum[:]),
			Path:        filepath.Join(name, "SKILL.md"),
		})
	}

	// Sort by name so the lockfile is deterministic.
	sort.Slice(lf.Skills, func(i, j int) bool { return lf.Skills[i].Name < lf.Skills[j].Name })
	return lf, nil
}

// WriteLockfile marshals lf to YAML and writes it to dir/MANIFEST.yaml.
// Atomic via temp + rename.
func WriteLockfile(dir string, lf Lockfile) error {
	path := filepath.Join(dir, LockfileName)
	tmp := path + ".tmp"

	data, err := yaml.Marshal(lf)
	if err != nil {
		return fmt.Errorf("marshal lockfile: %w", err)
	}
	header := []byte("# Generated by `aria-core skills lock`. Do not edit by hand.\n# Bump skills, then re-run lock to refresh hashes.\n")
	data = append(header, data...)

	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return fmt.Errorf("write tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}

// ReadLockfile reads dir/MANIFEST.yaml. Returns ErrLockfileMissing if
// the file doesn't exist (caller decides whether that is fatal).
func ReadLockfile(dir string) (Lockfile, error) {
	path := filepath.Join(dir, LockfileName)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return Lockfile{}, ErrLockfileMissing
		}
		return Lockfile{}, fmt.Errorf("read lockfile: %w", err)
	}
	var lf Lockfile
	if err := yaml.Unmarshal(data, &lf); err != nil {
		return Lockfile{}, fmt.Errorf("parse lockfile: %w", err)
	}
	return lf, nil
}

// ErrLockfileMissing is returned by ReadLockfile when MANIFEST.yaml
// doesn't exist. Callers in CI should treat it as a hard failure;
// callers locally may treat it as "run aria-core skills lock first".
var ErrLockfileMissing = fmt.Errorf("skills lockfile (MANIFEST.yaml) not found")

// DriftKind labels what kind of drift was detected for one entry.
type DriftKind string

const (
	DriftAdded   DriftKind = "added"   // present in working tree, missing from lockfile
	DriftRemoved DriftKind = "removed" // present in lockfile, missing from working tree
	DriftHash    DriftKind = "hash"    // content_sha256 differs
	DriftVersion DriftKind = "version" // version field differs
)

// DriftEntry is one drift finding.
type DriftEntry struct {
	Name string    `json:"name"`
	Kind DriftKind `json:"kind"`
	Note string    `json:"note,omitempty"`
}

// DriftReport aggregates drift between working tree and lockfile.
type DriftReport struct {
	Skills    int          `json:"skills"`
	Entries   []DriftEntry `json:"entries"`
	HasErrors bool         `json:"has_errors"`
}

// CheckDrift compares the working tree under dir against the lockfile
// at dir/MANIFEST.yaml and returns drift entries.
func CheckDrift(dir string) (DriftReport, error) {
	working, err := BuildLockfile(dir)
	if err != nil {
		return DriftReport{}, fmt.Errorf("build current state: %w", err)
	}
	committed, err := ReadLockfile(dir)
	if err != nil {
		return DriftReport{}, err
	}

	wantByName := map[string]LockEntry{}
	for _, e := range committed.Skills {
		wantByName[e.Name] = e
	}
	gotByName := map[string]LockEntry{}
	for _, e := range working.Skills {
		gotByName[e.Name] = e
	}

	var report DriftReport
	report.Skills = len(working.Skills)

	// Added: in working but not in lockfile
	for n, w := range gotByName {
		if _, ok := wantByName[n]; !ok {
			report.Entries = append(report.Entries, DriftEntry{
				Name: n, Kind: DriftAdded,
				Note: fmt.Sprintf("present in working tree (%s) but missing from lockfile — run `aria-core skills lock`", w.Path),
			})
			report.HasErrors = true
		}
	}
	// Removed: in lockfile but not in working
	for n := range wantByName {
		if _, ok := gotByName[n]; !ok {
			report.Entries = append(report.Entries, DriftEntry{
				Name: n, Kind: DriftRemoved,
				Note: "in lockfile but missing from working tree — re-add or remove from lockfile",
			})
			report.HasErrors = true
		}
	}
	// Hash / version mismatch
	for n, w := range gotByName {
		c, ok := wantByName[n]
		if !ok {
			continue
		}
		if w.ContentHash != c.ContentHash {
			report.Entries = append(report.Entries, DriftEntry{
				Name: n, Kind: DriftHash,
				Note: fmt.Sprintf("content changed (lockfile=%s working=%s)", short(c.ContentHash), short(w.ContentHash)),
			})
			report.HasErrors = true
		}
		if w.Version != c.Version {
			report.Entries = append(report.Entries, DriftEntry{
				Name: n, Kind: DriftVersion,
				Note: fmt.Sprintf("version changed (lockfile=%s working=%s)", c.Version, w.Version),
			})
			report.HasErrors = true
		}
	}

	// Sort for deterministic output
	sort.Slice(report.Entries, func(i, j int) bool {
		return report.Entries[i].Name+string(report.Entries[i].Kind) <
			report.Entries[j].Name+string(report.Entries[j].Kind)
	})
	return report, nil
}

func short(h string) string {
	if len(h) <= 12 {
		return h
	}
	return h[:12]
}
