package skills

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func writeSkill(t *testing.T, root, name, content string) {
	t.Helper()
	dir := filepath.Join(root, name)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "SKILL.md"), []byte(content), 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
}

func skillBody(name string) string {
	return "---\nname: " + name + "\ndescription: Description for " + name + " — at least 10 chars.\nversion: 1.0.0\nowner: a@b.com\n---\n\n## When to Use\n\nbody here\n\n## Verification\n\nverify\n"
}

func TestBuildLockfile_DeterministicOrdering(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "zeta", skillBody("zeta"))
	writeSkill(t, root, "alpha", skillBody("alpha"))
	writeSkill(t, root, "mu", skillBody("mu"))

	lf, err := BuildLockfile(root)
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if len(lf.Skills) != 3 {
		t.Fatalf("want 3 skills, got %d", len(lf.Skills))
	}
	want := []string{"alpha", "mu", "zeta"}
	for i, s := range lf.Skills {
		if s.Name != want[i] {
			t.Errorf("position %d: want %q got %q", i, want[i], s.Name)
		}
		if len(s.ContentHash) != 64 {
			t.Errorf("hash for %q: want 64 hex chars, got %q", s.Name, s.ContentHash)
		}
	}
}

func TestWriteAndReadLockfile_Roundtrip(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))

	lf, err := BuildLockfile(root)
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if err := WriteLockfile(root, lf); err != nil {
		t.Fatalf("write: %v", err)
	}

	read, err := ReadLockfile(root)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if len(read.Skills) != 1 || read.Skills[0].Name != "alpha" {
		t.Errorf("roundtrip mismatch: %+v", read)
	}
}

func TestReadLockfile_MissingReturnsSentinel(t *testing.T) {
	root := t.TempDir()
	_, err := ReadLockfile(root)
	if !errors.Is(err, ErrLockfileMissing) {
		t.Errorf("expected ErrLockfileMissing, got %v", err)
	}
}

func TestCheckDrift_NoDrift(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))
	lf, _ := BuildLockfile(root)
	_ = WriteLockfile(root, lf)

	report, err := CheckDrift(root)
	if err != nil {
		t.Fatalf("drift: %v", err)
	}
	if report.HasErrors {
		t.Errorf("expected no drift, got: %+v", report.Entries)
	}
}

func TestCheckDrift_AddedSkill(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))
	lf, _ := BuildLockfile(root)
	_ = WriteLockfile(root, lf)

	// Add a second skill without re-locking
	writeSkill(t, root, "beta", skillBody("beta"))

	report, err := CheckDrift(root)
	if err != nil {
		t.Fatalf("drift: %v", err)
	}
	hasAdded := false
	for _, e := range report.Entries {
		if e.Name == "beta" && e.Kind == DriftAdded {
			hasAdded = true
		}
	}
	if !hasAdded {
		t.Error("expected DriftAdded for beta")
	}
}

func TestCheckDrift_HashMismatch(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))
	lf, _ := BuildLockfile(root)
	_ = WriteLockfile(root, lf)

	// Tamper with the SKILL.md without re-locking
	content := skillBody("alpha") + "\n\nextra body content to change the hash.\n"
	_ = os.WriteFile(filepath.Join(root, "alpha", "SKILL.md"), []byte(content), 0o644)

	report, err := CheckDrift(root)
	if err != nil {
		t.Fatalf("drift: %v", err)
	}
	hasHash := false
	for _, e := range report.Entries {
		if e.Name == "alpha" && e.Kind == DriftHash {
			hasHash = true
		}
	}
	if !hasHash {
		t.Error("expected DriftHash for alpha")
	}
}

func TestCheckDrift_RemovedSkill(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))
	writeSkill(t, root, "beta", skillBody("beta"))
	lf, _ := BuildLockfile(root)
	_ = WriteLockfile(root, lf)

	if err := os.RemoveAll(filepath.Join(root, "beta")); err != nil {
		t.Fatalf("remove: %v", err)
	}

	report, err := CheckDrift(root)
	if err != nil {
		t.Fatalf("drift: %v", err)
	}
	hasRemoved := false
	for _, e := range report.Entries {
		if e.Name == "beta" && e.Kind == DriftRemoved {
			hasRemoved = true
		}
	}
	if !hasRemoved {
		t.Error("expected DriftRemoved for beta")
	}
}

func TestLockfileHasYAMLHeader(t *testing.T) {
	root := t.TempDir()
	writeSkill(t, root, "alpha", skillBody("alpha"))
	lf, _ := BuildLockfile(root)
	_ = WriteLockfile(root, lf)
	data, _ := os.ReadFile(filepath.Join(root, LockfileName))
	if !strings.HasPrefix(string(data), "# Generated by") {
		t.Errorf("missing header: %s", string(data)[:50])
	}
}
