package skills

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// VersionsFile is the canonical filename for the per-skill semver
// index. Lives at skills/VERSIONS.md.
const VersionsFile = "VERSIONS.md"

// BuildVersionsTable returns the rendered Markdown content for
// VERSIONS.md based on the current state of dir/<skill>/SKILL.md.
//
// Format inspired by coreyhaines31/marketingskills VERSIONS.md but
// adapted for ARIA's frontmatter (we have version + owner +
// last_reviewed; they don't).
func BuildVersionsTable(dir string) (string, error) {
	lf, err := BuildLockfile(dir)
	if err != nil {
		return "", fmt.Errorf("build lockfile for versions: %w", err)
	}

	// Read each skill's full frontmatter for last_reviewed and the
	// optional `agent` flag. We do this from disk because the
	// lockfile only carries a subset of fields.
	type row struct {
		Name         string
		Version      string
		Owner        string
		Agent        bool
		LastReviewed string
	}
	rows := make([]row, 0, len(lf.Skills))
	for _, e := range lf.Skills {
		r := row{Name: e.Name, Version: e.Version, Owner: e.Owner}
		path := filepath.Join(dir, e.Path)
		if data, ferr := os.ReadFile(path); ferr == nil {
			fm, perr := parseFrontmatterMap(data)
			if perr == nil {
				if v, ok := fm["agent"].(bool); ok {
					r.Agent = v
				}
				if v, ok := fm["last_reviewed"].(string); ok {
					r.LastReviewed = v
				}
			}
		}
		rows = append(rows, r)
	}

	sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })

	var b strings.Builder
	b.WriteString("# Skills VERSIONS\n\n")
	b.WriteString("> Auto-generated by `aria-core skills versions`. Do not edit by hand.\n")
	b.WriteString("> Re-run after bumping any skill `version` in frontmatter.\n\n")
	b.WriteString(fmt.Sprintf("Total: **%d** skills.\n\n", len(rows)))
	b.WriteString("| Skill | Version | Owner | Agent? | Last Reviewed |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range rows {
		agent := ""
		if r.Agent {
			agent = "✓"
		}
		owner := r.Owner
		if owner == "" {
			owner = "_(missing)_"
		}
		ver := r.Version
		if ver == "" {
			ver = "_(missing)_"
		}
		lr := r.LastReviewed
		if lr == "" {
			lr = "—"
		}
		b.WriteString(fmt.Sprintf("| `%s` | %s | %s | %s | %s |\n",
			r.Name, ver, owner, agent, lr))
	}
	return b.String(), nil
}

// WriteVersionsFile writes the rendered VERSIONS.md atomically.
func WriteVersionsFile(dir string) error {
	body, err := BuildVersionsTable(dir)
	if err != nil {
		return err
	}
	path := filepath.Join(dir, VersionsFile)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write tmp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("rename: %w", err)
	}
	return nil
}

// parseFrontmatterMap is a lightweight helper that reads a SKILL.md
// blob and returns its frontmatter as a generic map. Used only from
// versions.go and the future health dashboard handler.
func parseFrontmatterMap(data []byte) (map[string]any, error) {
	front, _, err := splitFrontmatter(data)
	if err != nil {
		return nil, err
	}
	return parseYAMLMap(front)
}

// parseYAMLMap is a thin indirection so we can stub yaml in tests.
var parseYAMLMap = func(b []byte) (map[string]any, error) {
	return parseYAML(b)
}
